import AdminNav from "../components/admin/AdminNav"

export const metadata = {
  title: 'E Shop',
  description: 'Generated by create next app',
}

const AdminLayout = ({children}:{children: React.ReactNode}) => {
  return (
    <div>

     <AdminNav/>
      {children}
    </div>
  )
}

export default AdminLayout