import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import NavBar from './components/nav/NavBar'
import Footer from './components/footer/Footer'
import CartProvider from '@/providers/CartProvider'
import {Toaster} from 'react-hot-toast'

const quicksand = Quicksand({ subsets: ['latin'], weight:['500', '700'] })

export const metadata: Metadata = {
  title: 'E Shop',
  description: 'Generated by create next app',
}

export default  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={`${quicksand.className} text-slate-700`}>
        <Toaster toastOptions={{style:{

          background:'rgb(51 65 85)',
          color: '#ccc',

        }}}/>
        <CartProvider>
        <div className='flex flex-col min-h-screen'>
        <NavBar/>
        <main className='flex-grow '>
        {children}
        </main>
        <Footer/>
        </div>
        </CartProvider>
        </body>
    </html>
  )
}
